# Generated by Django 5.2.16 on 2026-08-01 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Estimation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("wordpress_website", "طراحی سایت وردپرسی"),
                            ("custom_website", "طراحی سایت اختصاصی"),
                            ("telegram_bot", "ساخت ربات تلگرام"),
                            ("n8n_automation", "اتوماسیون با n8n"),
                            ("poster_design", "طراحی پوستر"),
                            ("thumbnail_cover_design", "طراحی تامنیل یوتیوب و کاور اینستاگرام"),
                        ],
                        max_length=32,
                    ),
                ),
                ("answers", models.JSONField(blank=True, default=dict)),
                ("price_min_toman", models.PositiveIntegerField()),
                ("price_max_toman", models.PositiveIntegerField()),
                ("duration_min_days", models.PositiveIntegerField()),
                ("duration_max_days", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estimations",
                        to="accounts.customer",
                    ),
                ),
            ],
            options={
                "db_table": "estimations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=20)),
                ("company_name", models.CharField(blank=True, max_length=255, null=True)),
                ("project_description", models.TextField()),
                ("proposed_budget", models.CharField(max_length=255)),
                ("desired_timeline", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_requests",
                        to="accounts.customer",
                    ),
                ),
                (
                    "estimation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_request",
                        to="requests.estimation",
                    ),
                ),
            ],
            options={
                "db_table": "project_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("telegram_file_id", models.CharField(max_length=255)),
                ("telegram_file_unique_id", models.CharField(max_length=255)),
                ("file_name", models.CharField(blank=True, max_length=255, null=True)),
                ("mime_type", models.CharField(blank=True, max_length=100, null=True)),
                ("file_size", models.PositiveIntegerField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="requests.projectrequest",
                    ),
                ),
            ],
            options={
                "db_table": "project_attachments",
            },
        ),
    ]
