# Generated by Django 5.2.16 on 2026-08-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectattachment",
            name="kind",
            field=models.CharField(
                choices=[("document", "Document"), ("photo", "Photo")],
                default="document",
                max_length=20,
            ),
        ),
    ]
