# Generated by Django 5.2.16 on 2026-08-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TelegramFSMState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("bot_id", models.BigIntegerField()),
                ("chat_id", models.BigIntegerField()),
                ("user_id", models.BigIntegerField()),
                ("thread_id", models.BigIntegerField(default=0)),
                ("destiny", models.CharField(default="default", max_length=32)),
                ("state", models.CharField(blank=True, max_length=255, null=True)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "telegram_fsm_states",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("bot_id", "chat_id", "user_id", "thread_id", "destiny"),
                        name="unique_fsm_storage_key",
                    )
                ],
            },
        ),
    ]
